/*
 * PAI-AB Server API
 *
 * PAI-AB Server API
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package api

import (
	"context"
	"strconv"

	"github.com/alibabacloud-go/paiabtest-20240119/client"
	util "github.com/alibabacloud-go/tea-utils/v2/service"
	"github.com/alibabacloud-go/tea/tea"
	"github.com/aliyun/aliyun-pai-ab-go-sdk/swagger"
)

// Linger please
var (
	_ context.Context
)

type LayerApiService service

func (a *LayerApiService) ListLayers(projectId int) ([]*swagger.Layer, error) {

	var ret []*swagger.Layer
	request := client.ListLayersRequest{
		ProjectId: tea.String(strconv.Itoa(projectId)),
		All:       tea.Bool(true),
	}

	runtime := &util.RuntimeOptions{
		IgnoreSSL: tea.Bool(true),
	}
	headers := make(map[string]*string)
	response, err := a.client.ListLayersWithOptions(&request, headers, runtime)
	if err != nil {
		return nil, err
	}

	for _, item := range response.Body.Layers {
		if id, err := strconv.Atoi(*item.LayerId); err == nil {
			layer := swagger.Layer{
				ExpLayerId:     int32(id),
				ExpProjectId:   int32(projectId),
				LayerName:      *item.Name,
				IsDefaultLayer: *item.IsDefaultLayer,
			}
			if id, err := strconv.Atoi(*item.DomainId); err == nil {
				layer.ExpDomainId = int32(id)
			}
			ret = append(ret, &layer)
		}
	}

	return ret, nil
}
